version: '2'

services:
  esm1:
    extends:
      file: elasticsearch-common.yml
      service: elasticsearch_master
  esd1:
    extends:
      file: elasticsearch-common.yml
      service: elasticsearch_data
  esd2:
    extends:
      file: elasticsearch-common.yml
      service: elasticsearch_data
  esd3:
    extends:
      file: elasticsearch-common.yml
      service: elasticsearch_data
  esc1:
    extends:
      file: elasticsearch-common.yml
      service: elasticsearch_client
    links:
      - esd1
      - esd2
      - esd3
  kb1:
    image: joshuar/kibana:4.5.2
    volumes:
      - ./kb/config:/opt/kibana/config
    links:
      - esc1:es
    ports:
      - 5601:5601
    environment:
      NODE_OPTIONS: --max-old-space-size=512
    depends_on:
      - esc1
