version: '2'

services:
  elasticsearch_master:
    image: joshuar/elasticsearch:2.3.5
    volumes:
      - ./es/config/master:/etc/elasticsearch
      - ./es/data:/var/lib/elasticsearch
      - ./es/logs:/var/log/elasticsearch
    expose:
      - 9200/tcp
      - 9300/tcp
    environment:
      ES_JAVA_OPTS: -XX:+PreserveFramePointer
      ES_HEAP_SIZE: 256m
    ulimits:
      memlock: -1
  elasticsearch_data:
    image: joshuar/elasticsearch:2.3.5
    volumes:
      - ./es/config/data:/etc/elasticsearch
      - ./es/data:/var/lib/elasticsearch
      - ./es/logs:/var/log/elasticsearch
    expose:
      - 9200/tcp
      - 9300/tcp
    environment:
      ES_JAVA_OPTS: -XX:+PreserveFramePointer
      ES_HEAP_SIZE: 512m
    ulimits:
      memlock: -1
  elasticsearch_client:
    image: joshuar/elasticsearch:2.3.5
    volumes:
      - ./es/config/client:/etc/elasticsearch
      - ./es/data:/var/lib/elasticsearch
      - ./es/logs:/var/log/elasticsearch
    expose:
      - 9200/tcp
      - 9300/tcp
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      ES_JAVA_OPTS: -XX:+PreserveFramePointer
      ES_HEAP_SIZE: 512m
    ulimits:
      memlock: -1
